name: dit
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=2.3.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # 关键！PyTorch官方预编译的CUDA 12.1版本
  - pip:
    - timm
    - diffusers
    - accelerate